// <auto-generated />
using Assignment_10_3_winforms_sqllite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_10_3_winforms_sqllite.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Assignment_10_3_winforms_sqllite.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Ford",
                            Model = "Mustang",
                            VIN = "1FA6P8CF0HXXXXXXX",
                            Year = 1980
                        },
                        new
                        {
                            Id = 2,
                            Make = "Chevrolet",
                            Model = "Corvette",
                            VIN = "1G1AY0780AXXXXXXX",
                            Year = 1980
                        },
                        new
                        {
                            Id = 3,
                            Make = "Toyota",
                            Model = "Celica",
                            VIN = "JZA8000XXXXXXXXXX",
                            Year = 1980
                        },
                        new
                        {
                            Id = 4,
                            Make = "Volkswagen",
                            Model = "Beetle",
                            VIN = "1V4BA31D0BXXXXXXX",
                            Year = 1980
                        },
                        new
                        {
                            Id = 5,
                            Make = "BMW",
                            Model = "3 Series",
                            VIN = "WBAAJ51000XXXXXXX",
                            Year = 1980
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
